sudo: required

language: minimal

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker pull docker/dockerfile:experimental
  - docker pull openjdk:8u232-jdk
  - docker pull adoptopenjdk:8u252-b09-jre-openj9-0.20.0
  - DOCKER_BUILDKIT=1 docker build -f docker/Dockerfile -t open-streaming:latest .
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag open-streaming $DOCKER_USERNAME/open-streaming:latest
  - docker push $DOCKER_USERNAME/open-streaming:latest

before_deploy:
  - docker tag open-streaming $DOCKER_USERNAME/open-streaming:$TRAVIS_TAG

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/open-streaming:$TRAVIS_TAG
  on:
    tags: true
