spring:
  jackson:
    serialization:
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false

openstreaming:
  broker-id: # XXX
  user-type: # INVESTOR, MKT_REP
  login-type: # TWO_LEGGED, THREE_LEGGED
  api-host: # https://open-api.settrade.com/
  two-legged:
    app-id: # ALGO
    api-key:
    api-secret:
  three-legged:
    login-host: # https://app.settrade.com/
    api-key:
    api-secret:
    redirect-url: # http://localhost:8080/login
    scope: # place_order user
  ip-filter:
    enabled: false
    allow: # pattern
    deny: # pattern
    deny-status: 403 # Forbidden
