// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidofferv1.proto

package com.settrade.openapi.protobuf.v1;

public interface BidOfferV1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:settrade.openapi.protobuf.v1.BidOfferV1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Subscribed symbol
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <pre>
   * Subscribed symbol
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * 1st bid price
   * Price equals to zero during ATO/ATC
   * </pre>
   *
   * <code>.google.type.Money bid_price1 = 2;</code>
   * @return Whether the bidPrice1 field is set.
   */
  boolean hasBidPrice1();
  /**
   * <pre>
   * 1st bid price
   * Price equals to zero during ATO/ATC
   * </pre>
   *
   * <code>.google.type.Money bid_price1 = 2;</code>
   * @return The bidPrice1.
   */
  com.google.type.Money getBidPrice1();
  /**
   * <pre>
   * 1st bid price
   * Price equals to zero during ATO/ATC
   * </pre>
   *
   * <code>.google.type.Money bid_price1 = 2;</code>
   */
  com.google.type.MoneyOrBuilder getBidPrice1OrBuilder();

  /**
   * <pre>
   * 2nd bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price2 = 3;</code>
   * @return Whether the bidPrice2 field is set.
   */
  boolean hasBidPrice2();
  /**
   * <pre>
   * 2nd bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price2 = 3;</code>
   * @return The bidPrice2.
   */
  com.google.type.Money getBidPrice2();
  /**
   * <pre>
   * 2nd bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price2 = 3;</code>
   */
  com.google.type.MoneyOrBuilder getBidPrice2OrBuilder();

  /**
   * <pre>
   * 3rd bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price3 = 4;</code>
   * @return Whether the bidPrice3 field is set.
   */
  boolean hasBidPrice3();
  /**
   * <pre>
   * 3rd bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price3 = 4;</code>
   * @return The bidPrice3.
   */
  com.google.type.Money getBidPrice3();
  /**
   * <pre>
   * 3rd bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price3 = 4;</code>
   */
  com.google.type.MoneyOrBuilder getBidPrice3OrBuilder();

  /**
   * <pre>
   * 4th bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price4 = 5;</code>
   * @return Whether the bidPrice4 field is set.
   */
  boolean hasBidPrice4();
  /**
   * <pre>
   * 4th bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price4 = 5;</code>
   * @return The bidPrice4.
   */
  com.google.type.Money getBidPrice4();
  /**
   * <pre>
   * 4th bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price4 = 5;</code>
   */
  com.google.type.MoneyOrBuilder getBidPrice4OrBuilder();

  /**
   * <pre>
   * 5th bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price5 = 6;</code>
   * @return Whether the bidPrice5 field is set.
   */
  boolean hasBidPrice5();
  /**
   * <pre>
   * 5th bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price5 = 6;</code>
   * @return The bidPrice5.
   */
  com.google.type.Money getBidPrice5();
  /**
   * <pre>
   * 5th bid price
   * </pre>
   *
   * <code>.google.type.Money bid_price5 = 6;</code>
   */
  com.google.type.MoneyOrBuilder getBidPrice5OrBuilder();

  /**
   * <pre>
   * 1st ask price
   * Price equals to zero during ATO/ATC
   * </pre>
   *
   * <code>.google.type.Money ask_price1 = 7;</code>
   * @return Whether the askPrice1 field is set.
   */
  boolean hasAskPrice1();
  /**
   * <pre>
   * 1st ask price
   * Price equals to zero during ATO/ATC
   * </pre>
   *
   * <code>.google.type.Money ask_price1 = 7;</code>
   * @return The askPrice1.
   */
  com.google.type.Money getAskPrice1();
  /**
   * <pre>
   * 1st ask price
   * Price equals to zero during ATO/ATC
   * </pre>
   *
   * <code>.google.type.Money ask_price1 = 7;</code>
   */
  com.google.type.MoneyOrBuilder getAskPrice1OrBuilder();

  /**
   * <pre>
   * 2nd ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price2 = 8;</code>
   * @return Whether the askPrice2 field is set.
   */
  boolean hasAskPrice2();
  /**
   * <pre>
   * 2nd ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price2 = 8;</code>
   * @return The askPrice2.
   */
  com.google.type.Money getAskPrice2();
  /**
   * <pre>
   * 2nd ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price2 = 8;</code>
   */
  com.google.type.MoneyOrBuilder getAskPrice2OrBuilder();

  /**
   * <pre>
   * 3rd ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price3 = 9;</code>
   * @return Whether the askPrice3 field is set.
   */
  boolean hasAskPrice3();
  /**
   * <pre>
   * 3rd ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price3 = 9;</code>
   * @return The askPrice3.
   */
  com.google.type.Money getAskPrice3();
  /**
   * <pre>
   * 3rd ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price3 = 9;</code>
   */
  com.google.type.MoneyOrBuilder getAskPrice3OrBuilder();

  /**
   * <pre>
   * 4th ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price4 = 10;</code>
   * @return Whether the askPrice4 field is set.
   */
  boolean hasAskPrice4();
  /**
   * <pre>
   * 4th ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price4 = 10;</code>
   * @return The askPrice4.
   */
  com.google.type.Money getAskPrice4();
  /**
   * <pre>
   * 4th ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price4 = 10;</code>
   */
  com.google.type.MoneyOrBuilder getAskPrice4OrBuilder();

  /**
   * <pre>
   * 5th ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price5 = 11;</code>
   * @return Whether the askPrice5 field is set.
   */
  boolean hasAskPrice5();
  /**
   * <pre>
   * 5th ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price5 = 11;</code>
   * @return The askPrice5.
   */
  com.google.type.Money getAskPrice5();
  /**
   * <pre>
   * 5th ask price
   * </pre>
   *
   * <code>.google.type.Money ask_price5 = 11;</code>
   */
  com.google.type.MoneyOrBuilder getAskPrice5OrBuilder();

  /**
   * <pre>
   * 1st bid volume
   * </pre>
   *
   * <code>int64 bid_volume1 = 12;</code>
   * @return The bidVolume1.
   */
  long getBidVolume1();

  /**
   * <pre>
   * 2nd bid volume
   * </pre>
   *
   * <code>int64 bid_volume2 = 13;</code>
   * @return The bidVolume2.
   */
  long getBidVolume2();

  /**
   * <pre>
   * 3rd bid volume
   * </pre>
   *
   * <code>int64 bid_volume3 = 14;</code>
   * @return The bidVolume3.
   */
  long getBidVolume3();

  /**
   * <pre>
   * 4th bid volume
   * </pre>
   *
   * <code>int64 bid_volume4 = 15;</code>
   * @return The bidVolume4.
   */
  long getBidVolume4();

  /**
   * <pre>
   * 5th bid volume
   * </pre>
   *
   * <code>int64 bid_volume5 = 16;</code>
   * @return The bidVolume5.
   */
  long getBidVolume5();

  /**
   * <pre>
   * 1st ask volume
   * </pre>
   *
   * <code>int64 ask_volume1 = 17;</code>
   * @return The askVolume1.
   */
  long getAskVolume1();

  /**
   * <pre>
   * 2nd ask volume
   * </pre>
   *
   * <code>int64 ask_volume2 = 18;</code>
   * @return The askVolume2.
   */
  long getAskVolume2();

  /**
   * <pre>
   * 3rd ask volume
   * </pre>
   *
   * <code>int64 ask_volume3 = 19;</code>
   * @return The askVolume3.
   */
  long getAskVolume3();

  /**
   * <pre>
   * 4th ask volume
   * </pre>
   *
   * <code>int64 ask_volume4 = 20;</code>
   * @return The askVolume4.
   */
  long getAskVolume4();

  /**
   * <pre>
   * 5th ask volume
   * </pre>
   *
   * <code>int64 ask_volume5 = 21;</code>
   * @return The askVolume5.
   */
  long getAskVolume5();
}
