// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidofferv1.proto

package com.settrade.openapi.protobuf.v1;

public final class BidOfferV1Proto {
  private BidOfferV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_settrade_openapi_protobuf_v1_BidOfferV1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_settrade_openapi_protobuf_v1_BidOfferV1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020bidofferv1.proto\022\034settrade.openapi.pro" +
      "tobuf.v1\032\027google/type/money.proto\032\036googl" +
      "e/protobuf/wrappers.proto\"\376\004\n\nBidOfferV1" +
      "\022\016\n\006symbol\030\001 \001(\t\022&\n\nbid_price1\030\002 \001(\0132\022.g" +
      "oogle.type.Money\022&\n\nbid_price2\030\003 \001(\0132\022.g" +
      "oogle.type.Money\022&\n\nbid_price3\030\004 \001(\0132\022.g" +
      "oogle.type.Money\022&\n\nbid_price4\030\005 \001(\0132\022.g" +
      "oogle.type.Money\022&\n\nbid_price5\030\006 \001(\0132\022.g" +
      "oogle.type.Money\022&\n\nask_price1\030\007 \001(\0132\022.g" +
      "oogle.type.Money\022&\n\nask_price2\030\010 \001(\0132\022.g" +
      "oogle.type.Money\022&\n\nask_price3\030\t \001(\0132\022.g" +
      "oogle.type.Money\022&\n\nask_price4\030\n \001(\0132\022.g" +
      "oogle.type.Money\022&\n\nask_price5\030\013 \001(\0132\022.g" +
      "oogle.type.Money\022\023\n\013bid_volume1\030\014 \001(\003\022\023\n" +
      "\013bid_volume2\030\r \001(\003\022\023\n\013bid_volume3\030\016 \001(\003\022" +
      "\023\n\013bid_volume4\030\017 \001(\003\022\023\n\013bid_volume5\030\020 \001(" +
      "\003\022\023\n\013ask_volume1\030\021 \001(\003\022\023\n\013ask_volume2\030\022 " +
      "\001(\003\022\023\n\013ask_volume3\030\023 \001(\003\022\023\n\013ask_volume4\030" +
      "\024 \001(\003\022\023\n\013ask_volume5\030\025 \001(\003B5\n com.settra" +
      "de.openapi.protobuf.v1B\017BidOfferV1ProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.type.MoneyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_settrade_openapi_protobuf_v1_BidOfferV1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_settrade_openapi_protobuf_v1_BidOfferV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_settrade_openapi_protobuf_v1_BidOfferV1_descriptor,
        new java.lang.String[] { "Symbol", "BidPrice1", "BidPrice2", "BidPrice3", "BidPrice4", "BidPrice5", "AskPrice1", "AskPrice2", "AskPrice3", "AskPrice4", "AskPrice5", "BidVolume1", "BidVolume2", "BidVolume3", "BidVolume4", "BidVolume5", "AskVolume1", "AskVolume2", "AskVolume3", "AskVolume4", "AskVolume5", });
    com.google.type.MoneyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
