// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: infov1.proto

package com.settrade.openapi.protobuf.v1;

/**
 * <pre>
 * Topic: proto/topic/infov1/&lt;symbol&gt;
 * Today's general instrument information
 * </pre>
 *
 * Protobuf type {@code settrade.openapi.protobuf.v1.InfoV1}
 */
public  final class InfoV1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:settrade.openapi.protobuf.v1.InfoV1)
    InfoV1OrBuilder {
private static final long serialVersionUID = 0L;
  // Use InfoV1.newBuilder() to construct.
  private InfoV1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InfoV1() {
    symbol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InfoV1();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InfoV1(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            symbol_ = s;
            break;
          }
          case 18: {
            com.google.type.Money.Builder subBuilder = null;
            if (high_ != null) {
              subBuilder = high_.toBuilder();
            }
            high_ = input.readMessage(com.google.type.Money.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(high_);
              high_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.type.Money.Builder subBuilder = null;
            if (low_ != null) {
              subBuilder = low_.toBuilder();
            }
            low_ = input.readMessage(com.google.type.Money.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(low_);
              low_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.type.Money.Builder subBuilder = null;
            if (last_ != null) {
              subBuilder = last_.toBuilder();
            }
            last_ = input.readMessage(com.google.type.Money.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(last_);
              last_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            totalVolume_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.settrade.openapi.protobuf.v1.InfoV1Proto.internal_static_settrade_openapi_protobuf_v1_InfoV1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.settrade.openapi.protobuf.v1.InfoV1Proto.internal_static_settrade_openapi_protobuf_v1_InfoV1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.settrade.openapi.protobuf.v1.InfoV1.class, com.settrade.openapi.protobuf.v1.InfoV1.Builder.class);
  }

  public static final int SYMBOL_FIELD_NUMBER = 1;
  private volatile java.lang.Object symbol_;
  /**
   * <pre>
   * Subscribed symbol
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Subscribed symbol
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIGH_FIELD_NUMBER = 2;
  private com.google.type.Money high_;
  /**
   * <pre>
   * Highest price
   * </pre>
   *
   * <code>.google.type.Money high = 2;</code>
   * @return Whether the high field is set.
   */
  public boolean hasHigh() {
    return high_ != null;
  }
  /**
   * <pre>
   * Highest price
   * </pre>
   *
   * <code>.google.type.Money high = 2;</code>
   * @return The high.
   */
  public com.google.type.Money getHigh() {
    return high_ == null ? com.google.type.Money.getDefaultInstance() : high_;
  }
  /**
   * <pre>
   * Highest price
   * </pre>
   *
   * <code>.google.type.Money high = 2;</code>
   */
  public com.google.type.MoneyOrBuilder getHighOrBuilder() {
    return getHigh();
  }

  public static final int LOW_FIELD_NUMBER = 3;
  private com.google.type.Money low_;
  /**
   * <pre>
   * Lowest price
   * </pre>
   *
   * <code>.google.type.Money low = 3;</code>
   * @return Whether the low field is set.
   */
  public boolean hasLow() {
    return low_ != null;
  }
  /**
   * <pre>
   * Lowest price
   * </pre>
   *
   * <code>.google.type.Money low = 3;</code>
   * @return The low.
   */
  public com.google.type.Money getLow() {
    return low_ == null ? com.google.type.Money.getDefaultInstance() : low_;
  }
  /**
   * <pre>
   * Lowest price
   * </pre>
   *
   * <code>.google.type.Money low = 3;</code>
   */
  public com.google.type.MoneyOrBuilder getLowOrBuilder() {
    return getLow();
  }

  public static final int LAST_FIELD_NUMBER = 4;
  private com.google.type.Money last_;
  /**
   * <pre>
   * Current price
   * </pre>
   *
   * <code>.google.type.Money last = 4;</code>
   * @return Whether the last field is set.
   */
  public boolean hasLast() {
    return last_ != null;
  }
  /**
   * <pre>
   * Current price
   * </pre>
   *
   * <code>.google.type.Money last = 4;</code>
   * @return The last.
   */
  public com.google.type.Money getLast() {
    return last_ == null ? com.google.type.Money.getDefaultInstance() : last_;
  }
  /**
   * <pre>
   * Current price
   * </pre>
   *
   * <code>.google.type.Money last = 4;</code>
   */
  public com.google.type.MoneyOrBuilder getLastOrBuilder() {
    return getLast();
  }

  public static final int TOTAL_VOLUME_FIELD_NUMBER = 5;
  private long totalVolume_;
  /**
   * <pre>
   * Total traded volume
   * </pre>
   *
   * <code>int64 total_volume = 5;</code>
   * @return The totalVolume.
   */
  public long getTotalVolume() {
    return totalVolume_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
    }
    if (high_ != null) {
      output.writeMessage(2, getHigh());
    }
    if (low_ != null) {
      output.writeMessage(3, getLow());
    }
    if (last_ != null) {
      output.writeMessage(4, getLast());
    }
    if (totalVolume_ != 0L) {
      output.writeInt64(5, totalVolume_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
    }
    if (high_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHigh());
    }
    if (low_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLow());
    }
    if (last_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLast());
    }
    if (totalVolume_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, totalVolume_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.settrade.openapi.protobuf.v1.InfoV1)) {
      return super.equals(obj);
    }
    com.settrade.openapi.protobuf.v1.InfoV1 other = (com.settrade.openapi.protobuf.v1.InfoV1) obj;

    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (hasHigh() != other.hasHigh()) return false;
    if (hasHigh()) {
      if (!getHigh()
          .equals(other.getHigh())) return false;
    }
    if (hasLow() != other.hasLow()) return false;
    if (hasLow()) {
      if (!getLow()
          .equals(other.getLow())) return false;
    }
    if (hasLast() != other.hasLast()) return false;
    if (hasLast()) {
      if (!getLast()
          .equals(other.getLast())) return false;
    }
    if (getTotalVolume()
        != other.getTotalVolume()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    if (hasHigh()) {
      hash = (37 * hash) + HIGH_FIELD_NUMBER;
      hash = (53 * hash) + getHigh().hashCode();
    }
    if (hasLow()) {
      hash = (37 * hash) + LOW_FIELD_NUMBER;
      hash = (53 * hash) + getLow().hashCode();
    }
    if (hasLast()) {
      hash = (37 * hash) + LAST_FIELD_NUMBER;
      hash = (53 * hash) + getLast().hashCode();
    }
    hash = (37 * hash) + TOTAL_VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalVolume());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.settrade.openapi.protobuf.v1.InfoV1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.settrade.openapi.protobuf.v1.InfoV1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Topic: proto/topic/infov1/&lt;symbol&gt;
   * Today's general instrument information
   * </pre>
   *
   * Protobuf type {@code settrade.openapi.protobuf.v1.InfoV1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:settrade.openapi.protobuf.v1.InfoV1)
      com.settrade.openapi.protobuf.v1.InfoV1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.settrade.openapi.protobuf.v1.InfoV1Proto.internal_static_settrade_openapi_protobuf_v1_InfoV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.settrade.openapi.protobuf.v1.InfoV1Proto.internal_static_settrade_openapi_protobuf_v1_InfoV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.settrade.openapi.protobuf.v1.InfoV1.class, com.settrade.openapi.protobuf.v1.InfoV1.Builder.class);
    }

    // Construct using com.settrade.openapi.protobuf.v1.InfoV1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      symbol_ = "";

      if (highBuilder_ == null) {
        high_ = null;
      } else {
        high_ = null;
        highBuilder_ = null;
      }
      if (lowBuilder_ == null) {
        low_ = null;
      } else {
        low_ = null;
        lowBuilder_ = null;
      }
      if (lastBuilder_ == null) {
        last_ = null;
      } else {
        last_ = null;
        lastBuilder_ = null;
      }
      totalVolume_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.settrade.openapi.protobuf.v1.InfoV1Proto.internal_static_settrade_openapi_protobuf_v1_InfoV1_descriptor;
    }

    @java.lang.Override
    public com.settrade.openapi.protobuf.v1.InfoV1 getDefaultInstanceForType() {
      return com.settrade.openapi.protobuf.v1.InfoV1.getDefaultInstance();
    }

    @java.lang.Override
    public com.settrade.openapi.protobuf.v1.InfoV1 build() {
      com.settrade.openapi.protobuf.v1.InfoV1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.settrade.openapi.protobuf.v1.InfoV1 buildPartial() {
      com.settrade.openapi.protobuf.v1.InfoV1 result = new com.settrade.openapi.protobuf.v1.InfoV1(this);
      result.symbol_ = symbol_;
      if (highBuilder_ == null) {
        result.high_ = high_;
      } else {
        result.high_ = highBuilder_.build();
      }
      if (lowBuilder_ == null) {
        result.low_ = low_;
      } else {
        result.low_ = lowBuilder_.build();
      }
      if (lastBuilder_ == null) {
        result.last_ = last_;
      } else {
        result.last_ = lastBuilder_.build();
      }
      result.totalVolume_ = totalVolume_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.settrade.openapi.protobuf.v1.InfoV1) {
        return mergeFrom((com.settrade.openapi.protobuf.v1.InfoV1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.settrade.openapi.protobuf.v1.InfoV1 other) {
      if (other == com.settrade.openapi.protobuf.v1.InfoV1.getDefaultInstance()) return this;
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        onChanged();
      }
      if (other.hasHigh()) {
        mergeHigh(other.getHigh());
      }
      if (other.hasLow()) {
        mergeLow(other.getLow());
      }
      if (other.hasLast()) {
        mergeLast(other.getLast());
      }
      if (other.getTotalVolume() != 0L) {
        setTotalVolume(other.getTotalVolume());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.settrade.openapi.protobuf.v1.InfoV1 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.settrade.openapi.protobuf.v1.InfoV1) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <pre>
     * Subscribed symbol
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Subscribed symbol
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Subscribed symbol
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Subscribed symbol
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      
      symbol_ = getDefaultInstance().getSymbol();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Subscribed symbol
     * </pre>
     *
     * <code>string symbol = 1;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symbol_ = value;
      onChanged();
      return this;
    }

    private com.google.type.Money high_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> highBuilder_;
    /**
     * <pre>
     * Highest price
     * </pre>
     *
     * <code>.google.type.Money high = 2;</code>
     * @return Whether the high field is set.
     */
    public boolean hasHigh() {
      return highBuilder_ != null || high_ != null;
    }
    /**
     * <pre>
     * Highest price
     * </pre>
     *
     * <code>.google.type.Money high = 2;</code>
     * @return The high.
     */
    public com.google.type.Money getHigh() {
      if (highBuilder_ == null) {
        return high_ == null ? com.google.type.Money.getDefaultInstance() : high_;
      } else {
        return highBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Highest price
     * </pre>
     *
     * <code>.google.type.Money high = 2;</code>
     */
    public Builder setHigh(com.google.type.Money value) {
      if (highBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        high_ = value;
        onChanged();
      } else {
        highBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Highest price
     * </pre>
     *
     * <code>.google.type.Money high = 2;</code>
     */
    public Builder setHigh(
        com.google.type.Money.Builder builderForValue) {
      if (highBuilder_ == null) {
        high_ = builderForValue.build();
        onChanged();
      } else {
        highBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Highest price
     * </pre>
     *
     * <code>.google.type.Money high = 2;</code>
     */
    public Builder mergeHigh(com.google.type.Money value) {
      if (highBuilder_ == null) {
        if (high_ != null) {
          high_ =
            com.google.type.Money.newBuilder(high_).mergeFrom(value).buildPartial();
        } else {
          high_ = value;
        }
        onChanged();
      } else {
        highBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Highest price
     * </pre>
     *
     * <code>.google.type.Money high = 2;</code>
     */
    public Builder clearHigh() {
      if (highBuilder_ == null) {
        high_ = null;
        onChanged();
      } else {
        high_ = null;
        highBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Highest price
     * </pre>
     *
     * <code>.google.type.Money high = 2;</code>
     */
    public com.google.type.Money.Builder getHighBuilder() {
      
      onChanged();
      return getHighFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Highest price
     * </pre>
     *
     * <code>.google.type.Money high = 2;</code>
     */
    public com.google.type.MoneyOrBuilder getHighOrBuilder() {
      if (highBuilder_ != null) {
        return highBuilder_.getMessageOrBuilder();
      } else {
        return high_ == null ?
            com.google.type.Money.getDefaultInstance() : high_;
      }
    }
    /**
     * <pre>
     * Highest price
     * </pre>
     *
     * <code>.google.type.Money high = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
        getHighFieldBuilder() {
      if (highBuilder_ == null) {
        highBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                getHigh(),
                getParentForChildren(),
                isClean());
        high_ = null;
      }
      return highBuilder_;
    }

    private com.google.type.Money low_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> lowBuilder_;
    /**
     * <pre>
     * Lowest price
     * </pre>
     *
     * <code>.google.type.Money low = 3;</code>
     * @return Whether the low field is set.
     */
    public boolean hasLow() {
      return lowBuilder_ != null || low_ != null;
    }
    /**
     * <pre>
     * Lowest price
     * </pre>
     *
     * <code>.google.type.Money low = 3;</code>
     * @return The low.
     */
    public com.google.type.Money getLow() {
      if (lowBuilder_ == null) {
        return low_ == null ? com.google.type.Money.getDefaultInstance() : low_;
      } else {
        return lowBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Lowest price
     * </pre>
     *
     * <code>.google.type.Money low = 3;</code>
     */
    public Builder setLow(com.google.type.Money value) {
      if (lowBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        low_ = value;
        onChanged();
      } else {
        lowBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Lowest price
     * </pre>
     *
     * <code>.google.type.Money low = 3;</code>
     */
    public Builder setLow(
        com.google.type.Money.Builder builderForValue) {
      if (lowBuilder_ == null) {
        low_ = builderForValue.build();
        onChanged();
      } else {
        lowBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Lowest price
     * </pre>
     *
     * <code>.google.type.Money low = 3;</code>
     */
    public Builder mergeLow(com.google.type.Money value) {
      if (lowBuilder_ == null) {
        if (low_ != null) {
          low_ =
            com.google.type.Money.newBuilder(low_).mergeFrom(value).buildPartial();
        } else {
          low_ = value;
        }
        onChanged();
      } else {
        lowBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Lowest price
     * </pre>
     *
     * <code>.google.type.Money low = 3;</code>
     */
    public Builder clearLow() {
      if (lowBuilder_ == null) {
        low_ = null;
        onChanged();
      } else {
        low_ = null;
        lowBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Lowest price
     * </pre>
     *
     * <code>.google.type.Money low = 3;</code>
     */
    public com.google.type.Money.Builder getLowBuilder() {
      
      onChanged();
      return getLowFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Lowest price
     * </pre>
     *
     * <code>.google.type.Money low = 3;</code>
     */
    public com.google.type.MoneyOrBuilder getLowOrBuilder() {
      if (lowBuilder_ != null) {
        return lowBuilder_.getMessageOrBuilder();
      } else {
        return low_ == null ?
            com.google.type.Money.getDefaultInstance() : low_;
      }
    }
    /**
     * <pre>
     * Lowest price
     * </pre>
     *
     * <code>.google.type.Money low = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
        getLowFieldBuilder() {
      if (lowBuilder_ == null) {
        lowBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                getLow(),
                getParentForChildren(),
                isClean());
        low_ = null;
      }
      return lowBuilder_;
    }

    private com.google.type.Money last_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> lastBuilder_;
    /**
     * <pre>
     * Current price
     * </pre>
     *
     * <code>.google.type.Money last = 4;</code>
     * @return Whether the last field is set.
     */
    public boolean hasLast() {
      return lastBuilder_ != null || last_ != null;
    }
    /**
     * <pre>
     * Current price
     * </pre>
     *
     * <code>.google.type.Money last = 4;</code>
     * @return The last.
     */
    public com.google.type.Money getLast() {
      if (lastBuilder_ == null) {
        return last_ == null ? com.google.type.Money.getDefaultInstance() : last_;
      } else {
        return lastBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Current price
     * </pre>
     *
     * <code>.google.type.Money last = 4;</code>
     */
    public Builder setLast(com.google.type.Money value) {
      if (lastBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        last_ = value;
        onChanged();
      } else {
        lastBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Current price
     * </pre>
     *
     * <code>.google.type.Money last = 4;</code>
     */
    public Builder setLast(
        com.google.type.Money.Builder builderForValue) {
      if (lastBuilder_ == null) {
        last_ = builderForValue.build();
        onChanged();
      } else {
        lastBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Current price
     * </pre>
     *
     * <code>.google.type.Money last = 4;</code>
     */
    public Builder mergeLast(com.google.type.Money value) {
      if (lastBuilder_ == null) {
        if (last_ != null) {
          last_ =
            com.google.type.Money.newBuilder(last_).mergeFrom(value).buildPartial();
        } else {
          last_ = value;
        }
        onChanged();
      } else {
        lastBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Current price
     * </pre>
     *
     * <code>.google.type.Money last = 4;</code>
     */
    public Builder clearLast() {
      if (lastBuilder_ == null) {
        last_ = null;
        onChanged();
      } else {
        last_ = null;
        lastBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Current price
     * </pre>
     *
     * <code>.google.type.Money last = 4;</code>
     */
    public com.google.type.Money.Builder getLastBuilder() {
      
      onChanged();
      return getLastFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Current price
     * </pre>
     *
     * <code>.google.type.Money last = 4;</code>
     */
    public com.google.type.MoneyOrBuilder getLastOrBuilder() {
      if (lastBuilder_ != null) {
        return lastBuilder_.getMessageOrBuilder();
      } else {
        return last_ == null ?
            com.google.type.Money.getDefaultInstance() : last_;
      }
    }
    /**
     * <pre>
     * Current price
     * </pre>
     *
     * <code>.google.type.Money last = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
        getLastFieldBuilder() {
      if (lastBuilder_ == null) {
        lastBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                getLast(),
                getParentForChildren(),
                isClean());
        last_ = null;
      }
      return lastBuilder_;
    }

    private long totalVolume_ ;
    /**
     * <pre>
     * Total traded volume
     * </pre>
     *
     * <code>int64 total_volume = 5;</code>
     * @return The totalVolume.
     */
    public long getTotalVolume() {
      return totalVolume_;
    }
    /**
     * <pre>
     * Total traded volume
     * </pre>
     *
     * <code>int64 total_volume = 5;</code>
     * @param value The totalVolume to set.
     * @return This builder for chaining.
     */
    public Builder setTotalVolume(long value) {
      
      totalVolume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total traded volume
     * </pre>
     *
     * <code>int64 total_volume = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalVolume() {
      
      totalVolume_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:settrade.openapi.protobuf.v1.InfoV1)
  }

  // @@protoc_insertion_point(class_scope:settrade.openapi.protobuf.v1.InfoV1)
  private static final com.settrade.openapi.protobuf.v1.InfoV1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.settrade.openapi.protobuf.v1.InfoV1();
  }

  public static com.settrade.openapi.protobuf.v1.InfoV1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InfoV1>
      PARSER = new com.google.protobuf.AbstractParser<InfoV1>() {
    @java.lang.Override
    public InfoV1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InfoV1(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InfoV1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InfoV1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.settrade.openapi.protobuf.v1.InfoV1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

