// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: infov1.proto

package com.settrade.openapi.protobuf.v1;

public final class InfoV1Proto {
  private InfoV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_settrade_openapi_protobuf_v1_InfoV1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_settrade_openapi_protobuf_v1_InfoV1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014infov1.proto\022\034settrade.openapi.protobu" +
      "f.v1\032\027google/type/money.proto\"\223\001\n\006InfoV1" +
      "\022\016\n\006symbol\030\001 \001(\t\022 \n\004high\030\002 \001(\0132\022.google." +
      "type.Money\022\037\n\003low\030\003 \001(\0132\022.google.type.Mo" +
      "ney\022 \n\004last\030\004 \001(\0132\022.google.type.Money\022\024\n" +
      "\014total_volume\030\005 \001(\003B1\n com.settrade.open" +
      "api.protobuf.v1B\013InfoV1ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.type.MoneyProto.getDescriptor(),
        });
    internal_static_settrade_openapi_protobuf_v1_InfoV1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_settrade_openapi_protobuf_v1_InfoV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_settrade_openapi_protobuf_v1_InfoV1_descriptor,
        new java.lang.String[] { "Symbol", "High", "Low", "Last", "TotalVolume", });
    com.google.type.MoneyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
