// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ordereqv1.proto

package com.settrade.openapi.protobuf.v1;

public final class OrderEquityV1Proto {
  private OrderEquityV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ordereqv1.proto\022\034settrade.openapi.prot" +
      "obuf.v1\032\027google/type/money.proto\032\026google" +
      "/type/date.proto\032\033google/type/timeofday." +
      "proto\"\337\005\n\rOrderEquityV1\022\017\n\007version\030\001 \001(\005" +
      "\022\020\n\010order_no\030\002 \001(\t\022\024\n\014ext_order_no\030\003 \001(\t" +
      "\022\022\n\naccount_no\030\004 \001(\t\022*\n\nentry_time\030\005 \001(\013" +
      "2\026.google.type.TimeOfDay\022%\n\ntrade_date\030\006" +
      " \001(\0132\021.google.type.Date\022\016\n\006symbol\030\007 \001(\t\022" +
      "\017\n\007is_nvdr\030\010 \001(\010\022!\n\005price\030\t \001(\0132\022.google" +
      ".type.Money\022I\n\nprice_type\030\n \001(\01625.settra" +
      "de.openapi.protobuf.v1.OrderEquityV1.Pri" +
      "ceType\022A\n\004side\030\013 \001(\01623.settrade.openapi." +
      "protobuf.v1.OrderEquityV1.BuySell\022\016\n\006vol" +
      "ume\030\014 \001(\003\022\026\n\016matched_volume\030\r \001(\003\022\026\n\016bal" +
      "ance_volume\030\016 \001(\003\022\030\n\020cancelled_volume\030\017 " +
      "\001(\003\022\016\n\006status\030\020 \001(\t\022\022\n\ncan_cancel\030\021 \001(\010\022" +
      "\022\n\ncan_change\030\022 \001(\010\022\034\n\024can_change_price_" +
      "vol\030\023 \001(\010\"w\n\tPriceType\022\030\n\024UNDEFINED_PRIC" +
      "E_TYPE\020\000\022\t\n\005LIMIT\020\001\022\007\n\003ATO\020\002\022\007\n\003ATC\020\003\022\n\n" +
      "\006MARKET\020\004\022\022\n\016SPECIAL_MARKET\020\005\022\023\n\017MARKET_" +
      "TO_LIMIT\020\006\"3\n\007BuySell\022\025\n\021UNDEFINED_BUYSE" +
      "LL\020\000\022\007\n\003BUY\020\001\022\010\n\004SELL\020\002B8\n com.settrade." +
      "openapi.protobuf.v1B\022OrderEquityV1ProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.type.MoneyProto.getDescriptor(),
          com.google.type.DateProto.getDescriptor(),
          com.google.type.TimeOfDayProto.getDescriptor(),
        });
    internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_descriptor,
        new java.lang.String[] { "Version", "OrderNo", "ExtOrderNo", "AccountNo", "EntryTime", "TradeDate", "Symbol", "IsNvdr", "Price", "PriceType", "Side", "Volume", "MatchedVolume", "BalanceVolume", "CancelledVolume", "Status", "CanCancel", "CanChange", "CanChangePriceVol", });
    com.google.type.MoneyProto.getDescriptor();
    com.google.type.DateProto.getDescriptor();
    com.google.type.TimeOfDayProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
