// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderdvv1.proto

package com.settrade.openapi.protobuf.v1;

public interface OrderDerivV1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:settrade.openapi.protobuf.v1.OrderDerivV1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Order version. Greater version means more recent order
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * Settrade order no.
   * </pre>
   *
   * <code>string order_no = 2;</code>
   * @return The orderNo.
   */
  java.lang.String getOrderNo();
  /**
   * <pre>
   * Settrade order no.
   * </pre>
   *
   * <code>string order_no = 2;</code>
   * @return The bytes for orderNo.
   */
  com.google.protobuf.ByteString
      getOrderNoBytes();

  /**
   * <pre>
   * External order no. in case of using integrated account, otherwise blank
   * </pre>
   *
   * <code>string ext_order_no = 3;</code>
   * @return The extOrderNo.
   */
  java.lang.String getExtOrderNo();
  /**
   * <pre>
   * External order no. in case of using integrated account, otherwise blank
   * </pre>
   *
   * <code>string ext_order_no = 3;</code>
   * @return The bytes for extOrderNo.
   */
  com.google.protobuf.ByteString
      getExtOrderNoBytes();

  /**
   * <pre>
   * Subscribed account no.
   * </pre>
   *
   * <code>string account_no = 4;</code>
   * @return The accountNo.
   */
  java.lang.String getAccountNo();
  /**
   * <pre>
   * Subscribed account no.
   * </pre>
   *
   * <code>string account_no = 4;</code>
   * @return The bytes for accountNo.
   */
  com.google.protobuf.ByteString
      getAccountNoBytes();

  /**
   * <pre>
   * ID of Market Representative who placed this order
   * Blank if investor place order by him or herself
   * </pre>
   *
   * <code>string enter_id = 5;</code>
   * @return The enterId.
   */
  java.lang.String getEnterId();
  /**
   * <pre>
   * ID of Market Representative who placed this order
   * Blank if investor place order by him or herself
   * </pre>
   *
   * <code>string enter_id = 5;</code>
   * @return The bytes for enterId.
   */
  com.google.protobuf.ByteString
      getEnterIdBytes();

  /**
   * <pre>
   * The time the order is submitted
   * </pre>
   *
   * <code>.google.protobuf.Timestamp entry_time = 6;</code>
   * @return Whether the entryTime field is set.
   */
  boolean hasEntryTime();
  /**
   * <pre>
   * The time the order is submitted
   * </pre>
   *
   * <code>.google.protobuf.Timestamp entry_time = 6;</code>
   * @return The entryTime.
   */
  com.google.protobuf.Timestamp getEntryTime();
  /**
   * <pre>
   * The time the order is submitted
   * </pre>
   *
   * <code>.google.protobuf.Timestamp entry_time = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEntryTimeOrBuilder();

  /**
   * <pre>
   * Series ID or symbol
   * </pre>
   *
   * <code>string series_id = 7;</code>
   * @return The seriesId.
   */
  java.lang.String getSeriesId();
  /**
   * <pre>
   * Series ID or symbol
   * </pre>
   *
   * <code>string series_id = 7;</code>
   * @return The bytes for seriesId.
   */
  com.google.protobuf.ByteString
      getSeriesIdBytes();

  /**
   * <pre>
   * Side - Long, Short or both
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderDerivV1.LongShort side = 8;</code>
   * @return The enum numeric value on the wire for side.
   */
  int getSideValue();
  /**
   * <pre>
   * Side - Long, Short or both
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderDerivV1.LongShort side = 8;</code>
   * @return The side.
   */
  com.settrade.openapi.protobuf.v1.OrderDerivV1.LongShort getSide();

  /**
   * <pre>
   * Position - Open, Close, Auto
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderDerivV1.Position position = 9;</code>
   * @return The enum numeric value on the wire for position.
   */
  int getPositionValue();
  /**
   * <pre>
   * Position - Open, Close, Auto
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderDerivV1.Position position = 9;</code>
   * @return The position.
   */
  com.settrade.openapi.protobuf.v1.OrderDerivV1.Position getPosition();

  /**
   * <pre>
   * Order Price
   * </pre>
   *
   * <code>.google.type.Money price = 10;</code>
   * @return Whether the price field is set.
   */
  boolean hasPrice();
  /**
   * <pre>
   * Order Price
   * </pre>
   *
   * <code>.google.type.Money price = 10;</code>
   * @return The price.
   */
  com.google.type.Money getPrice();
  /**
   * <pre>
   * Order Price
   * </pre>
   *
   * <code>.google.type.Money price = 10;</code>
   */
  com.google.type.MoneyOrBuilder getPriceOrBuilder();

  /**
   * <pre>
   * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderDerivV1.PriceType price_type = 11;</code>
   * @return The enum numeric value on the wire for priceType.
   */
  int getPriceTypeValue();
  /**
   * <pre>
   * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderDerivV1.PriceType price_type = 11;</code>
   * @return The priceType.
   */
  com.settrade.openapi.protobuf.v1.OrderDerivV1.PriceType getPriceType();

  /**
   * <pre>
   * Order Volume
   * </pre>
   *
   * <code>int64 volume = 12;</code>
   * @return The volume.
   */
  long getVolume();

  /**
   * <pre>
   * Order Balance Volume
   * Balance Volume = Order Volume - Matched Volume - Cancelled Volume
   * </pre>
   *
   * <code>int64 balance_volume = 13;</code>
   * @return The balanceVolume.
   */
  long getBalanceVolume();

  /**
   * <pre>
   * Order Matched Volume
   * </pre>
   *
   * <code>int64 matched_volume = 14;</code>
   * @return The matchedVolume.
   */
  long getMatchedVolume();

  /**
   * <pre>
   * Order Cancelled Volume
   * </pre>
   *
   * <code>int64 cancelled_volume = 15;</code>
   * @return The cancelledVolume.
   */
  long getCancelledVolume();

  /**
   * <pre>
   * Validity of order - FOK, IOC, GTD, GTC, GTT, GTS, AUCTION, DAY, AUTO-M
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderDerivV1.Valid valid = 16;</code>
   * @return The enum numeric value on the wire for valid.
   */
  int getValidValue();
  /**
   * <pre>
   * Validity of order - FOK, IOC, GTD, GTC, GTT, GTS, AUCTION, DAY, AUTO-M
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderDerivV1.Valid valid = 16;</code>
   * @return The valid.
   */
  com.settrade.openapi.protobuf.v1.OrderDerivV1.Valid getValid();

  /**
   * <pre>
   * Additional information regarding date, time and session if order validity is GTD, GTT and GTS respectively
   * </pre>
   *
   * <code>string until = 17;</code>
   * @return The until.
   */
  java.lang.String getUntil();
  /**
   * <pre>
   * Additional information regarding date, time and session if order validity is GTD, GTT and GTS respectively
   * </pre>
   *
   * <code>string until = 17;</code>
   * @return The bytes for until.
   */
  com.google.protobuf.ByteString
      getUntilBytes();

  /**
   * <pre>
   * Order Status
   * </pre>
   *
   * <code>string status = 18;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Order Status
   * </pre>
   *
   * <code>string status = 18;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   * True if available for cancel, false otherwise
   * </pre>
   *
   * <code>bool can_cancel = 19;</code>
   * @return The canCancel.
   */
  boolean getCanCancel();

  /**
   * <pre>
   * True if available for change nvdr, false otherwise
   * </pre>
   *
   * <code>bool can_change = 20;</code>
   * @return The canChange.
   */
  boolean getCanChange();

  /**
   * <pre>
   * True if available for change price/volume, false otherwise
   * </pre>
   *
   * <code>bool can_change_price_vol = 21;</code>
   * @return The canChangePriceVol.
   */
  boolean getCanChangePriceVol();

  /**
   * <pre>
   * True if this order is trade report
   * </pre>
   *
   * <code>bool is_trade_report = 22;</code>
   * @return The isTradeReport.
   */
  boolean getIsTradeReport();
}
