// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ordereqv1.proto

package com.settrade.openapi.protobuf.v1;

public interface OrderEquityV1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:settrade.openapi.protobuf.v1.OrderEquityV1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Order version. Greater version means more recent order
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * Settrade Order No.
   * </pre>
   *
   * <code>string order_no = 2;</code>
   * @return The orderNo.
   */
  java.lang.String getOrderNo();
  /**
   * <pre>
   * Settrade Order No.
   * </pre>
   *
   * <code>string order_no = 2;</code>
   * @return The bytes for orderNo.
   */
  com.google.protobuf.ByteString
      getOrderNoBytes();

  /**
   * <pre>
   * External order no. in case of using integrated account, otherwise blank
   * </pre>
   *
   * <code>string ext_order_no = 3;</code>
   * @return The extOrderNo.
   */
  java.lang.String getExtOrderNo();
  /**
   * <pre>
   * External order no. in case of using integrated account, otherwise blank
   * </pre>
   *
   * <code>string ext_order_no = 3;</code>
   * @return The bytes for extOrderNo.
   */
  com.google.protobuf.ByteString
      getExtOrderNoBytes();

  /**
   * <pre>
   * Subscribed account no.
   * </pre>
   *
   * <code>string account_no = 4;</code>
   * @return The accountNo.
   */
  java.lang.String getAccountNo();
  /**
   * <pre>
   * Subscribed account no.
   * </pre>
   *
   * <code>string account_no = 4;</code>
   * @return The bytes for accountNo.
   */
  com.google.protobuf.ByteString
      getAccountNoBytes();

  /**
   * <pre>
   * The time the order is submitted
   * </pre>
   *
   * <code>.google.type.TimeOfDay entry_time = 5;</code>
   * @return Whether the entryTime field is set.
   */
  boolean hasEntryTime();
  /**
   * <pre>
   * The time the order is submitted
   * </pre>
   *
   * <code>.google.type.TimeOfDay entry_time = 5;</code>
   * @return The entryTime.
   */
  com.google.type.TimeOfDay getEntryTime();
  /**
   * <pre>
   * The time the order is submitted
   * </pre>
   *
   * <code>.google.type.TimeOfDay entry_time = 5;</code>
   */
  com.google.type.TimeOfDayOrBuilder getEntryTimeOrBuilder();

  /**
   * <pre>
   * Order Trade Date
   * </pre>
   *
   * <code>.google.type.Date trade_date = 6;</code>
   * @return Whether the tradeDate field is set.
   */
  boolean hasTradeDate();
  /**
   * <pre>
   * Order Trade Date
   * </pre>
   *
   * <code>.google.type.Date trade_date = 6;</code>
   * @return The tradeDate.
   */
  com.google.type.Date getTradeDate();
  /**
   * <pre>
   * Order Trade Date
   * </pre>
   *
   * <code>.google.type.Date trade_date = 6;</code>
   */
  com.google.type.DateOrBuilder getTradeDateOrBuilder();

  /**
   * <pre>
   * Order Symbol
   * </pre>
   *
   * <code>string symbol = 7;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <pre>
   * Order Symbol
   * </pre>
   *
   * <code>string symbol = 7;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * True if this is an NVDR order, false otherwise
   * </pre>
   *
   * <code>bool is_nvdr = 8;</code>
   * @return The isNvdr.
   */
  boolean getIsNvdr();

  /**
   * <pre>
   * Order Price
   * </pre>
   *
   * <code>.google.type.Money price = 9;</code>
   * @return Whether the price field is set.
   */
  boolean hasPrice();
  /**
   * <pre>
   * Order Price
   * </pre>
   *
   * <code>.google.type.Money price = 9;</code>
   * @return The price.
   */
  com.google.type.Money getPrice();
  /**
   * <pre>
   * Order Price
   * </pre>
   *
   * <code>.google.type.Money price = 9;</code>
   */
  com.google.type.MoneyOrBuilder getPriceOrBuilder();

  /**
   * <pre>
   * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType price_type = 10;</code>
   * @return The enum numeric value on the wire for priceType.
   */
  int getPriceTypeValue();
  /**
   * <pre>
   * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType price_type = 10;</code>
   * @return The priceType.
   */
  com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType getPriceType();

  /**
   * <pre>
   * Side - Buy or Sell
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell side = 11;</code>
   * @return The enum numeric value on the wire for side.
   */
  int getSideValue();
  /**
   * <pre>
   * Side - Buy or Sell
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell side = 11;</code>
   * @return The side.
   */
  com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell getSide();

  /**
   * <pre>
   * Order Volume
   * </pre>
   *
   * <code>int64 volume = 12;</code>
   * @return The volume.
   */
  long getVolume();

  /**
   * <pre>
   * Order Matched Volume
   * </pre>
   *
   * <code>int64 matched_volume = 13;</code>
   * @return The matchedVolume.
   */
  long getMatchedVolume();

  /**
   * <pre>
   * Order Balance Volume
   * Balance Volume = Order Volume - Matched Volume - Cancelled Volume
   * </pre>
   *
   * <code>int64 balance_volume = 14;</code>
   * @return The balanceVolume.
   */
  long getBalanceVolume();

  /**
   * <pre>
   * Order Cancelled Volume
   * </pre>
   *
   * <code>int64 cancelled_volume = 15;</code>
   * @return The cancelledVolume.
   */
  long getCancelledVolume();

  /**
   * <pre>
   * Order Status
   * </pre>
   *
   * <code>string status = 16;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Order Status
   * </pre>
   *
   * <code>string status = 16;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   * True if available for cancel, false otherwise
   * </pre>
   *
   * <code>bool can_cancel = 17;</code>
   * @return The canCancel.
   */
  boolean getCanCancel();

  /**
   * <pre>
   * True if available for change nvdr, false otherwise
   * </pre>
   *
   * <code>bool can_change = 18;</code>
   * @return The canChange.
   */
  boolean getCanChange();

  /**
   * <pre>
   * True if available for change price/volume, false otherwise
   * </pre>
   *
   * <code>bool can_change_price_vol = 19;</code>
   * @return The canChangePriceVol.
   */
  boolean getCanChangePriceVol();
}
