// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderdvv1.proto

package com.settrade.openapi.protobuf.v1;

public final class OrderDerivV1Proto {
  private OrderDerivV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_settrade_openapi_protobuf_v1_OrderDerivV1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_settrade_openapi_protobuf_v1_OrderDerivV1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017orderdvv1.proto\022\034settrade.openapi.prot" +
      "obuf.v1\032\037google/protobuf/timestamp.proto" +
      "\032\027google/type/money.proto\"\302\010\n\014OrderDeriv" +
      "V1\022\017\n\007version\030\001 \001(\005\022\020\n\010order_no\030\002 \001(\t\022\024\n" +
      "\014ext_order_no\030\003 \001(\t\022\022\n\naccount_no\030\004 \001(\t\022" +
      "\020\n\010enter_id\030\005 \001(\t\022.\n\nentry_time\030\006 \001(\0132\032." +
      "google.protobuf.Timestamp\022\021\n\tseries_id\030\007" +
      " \001(\t\022B\n\004side\030\010 \001(\01624.settrade.openapi.pr" +
      "otobuf.v1.OrderDerivV1.LongShort\022E\n\010posi" +
      "tion\030\t \001(\01623.settrade.openapi.protobuf.v" +
      "1.OrderDerivV1.Position\022!\n\005price\030\n \001(\0132\022" +
      ".google.type.Money\022H\n\nprice_type\030\013 \001(\01624" +
      ".settrade.openapi.protobuf.v1.OrderDeriv" +
      "V1.PriceType\022\016\n\006volume\030\014 \001(\003\022\026\n\016balance_" +
      "volume\030\r \001(\003\022\026\n\016matched_volume\030\016 \001(\003\022\030\n\020" +
      "cancelled_volume\030\017 \001(\003\022?\n\005valid\030\020 \001(\01620." +
      "settrade.openapi.protobuf.v1.OrderDerivV" +
      "1.Valid\022\r\n\005until\030\021 \001(\t\022\016\n\006status\030\022 \001(\t\022\022" +
      "\n\ncan_cancel\030\023 \001(\010\022\022\n\ncan_change\030\024 \001(\010\022\034" +
      "\n\024can_change_price_vol\030\025 \001(\010\022\027\n\017is_trade" +
      "_report\030\026 \001(\010\"w\n\tPriceType\022\030\n\024UNDEFINED_" +
      "PRICE_TYPE\020\000\022\t\n\005LIMIT\020\001\022\007\n\003ATO\020\002\022\007\n\003ATC\020" +
      "\003\022\n\n\006MARKET\020\004\022\022\n\016SPECIAL_MARKET\020\005\022\023\n\017MAR" +
      "KET_TO_LIMIT\020\006\"M\n\tLongShort\022\027\n\023UNDEFINED" +
      "_LONGSHORT\020\000\022\010\n\004LONG\020\001\022\t\n\005SHORT\020\002\022\022\n\016LON" +
      "G_AND_SHORT\020\003\"A\n\010Position\022\026\n\022UNDEFINED_P" +
      "OSITION\020\000\022\010\n\004OPEN\020\001\022\t\n\005CLOSE\020\002\022\010\n\004AUTO\020\003" +
      "\"t\n\005Valid\022\023\n\017UNDEFINED_VALID\020\000\022\007\n\003FOK\020\001\022" +
      "\007\n\003IOC\020\002\022\007\n\003GTD\020\003\022\007\n\003GTC\020\004\022\007\n\003GTT\020\005\022\007\n\003G" +
      "TS\020\006\022\013\n\007AUCTION\020\007\022\007\n\003DAY\020\010\022\n\n\006AUTO_M\020\tB7" +
      "\n com.settrade.openapi.protobuf.v1B\021Orde" +
      "rDerivV1ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.type.MoneyProto.getDescriptor(),
        });
    internal_static_settrade_openapi_protobuf_v1_OrderDerivV1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_settrade_openapi_protobuf_v1_OrderDerivV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_settrade_openapi_protobuf_v1_OrderDerivV1_descriptor,
        new java.lang.String[] { "Version", "OrderNo", "ExtOrderNo", "AccountNo", "EnterId", "EntryTime", "SeriesId", "Side", "Position", "Price", "PriceType", "Volume", "BalanceVolume", "MatchedVolume", "CancelledVolume", "Valid", "Until", "Status", "CanCancel", "CanChange", "CanChangePriceVol", "IsTradeReport", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.type.MoneyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
