// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ordereqv1.proto

package com.settrade.openapi.protobuf.v1;

/**
 * <pre>
 * Topic: proto/ua/_broker/&lt;account_no&gt;/_front/ordereqv1
 * Equity order information
 * </pre>
 *
 * Protobuf type {@code settrade.openapi.protobuf.v1.OrderEquityV1}
 */
public  final class OrderEquityV1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:settrade.openapi.protobuf.v1.OrderEquityV1)
    OrderEquityV1OrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderEquityV1.newBuilder() to construct.
  private OrderEquityV1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderEquityV1() {
    orderNo_ = "";
    extOrderNo_ = "";
    accountNo_ = "";
    symbol_ = "";
    priceType_ = 0;
    side_ = 0;
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderEquityV1();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderEquityV1(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            orderNo_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            extOrderNo_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            accountNo_ = s;
            break;
          }
          case 42: {
            com.google.type.TimeOfDay.Builder subBuilder = null;
            if (entryTime_ != null) {
              subBuilder = entryTime_.toBuilder();
            }
            entryTime_ = input.readMessage(com.google.type.TimeOfDay.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(entryTime_);
              entryTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.type.Date.Builder subBuilder = null;
            if (tradeDate_ != null) {
              subBuilder = tradeDate_.toBuilder();
            }
            tradeDate_ = input.readMessage(com.google.type.Date.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tradeDate_);
              tradeDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            symbol_ = s;
            break;
          }
          case 64: {

            isNvdr_ = input.readBool();
            break;
          }
          case 74: {
            com.google.type.Money.Builder subBuilder = null;
            if (price_ != null) {
              subBuilder = price_.toBuilder();
            }
            price_ = input.readMessage(com.google.type.Money.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(price_);
              price_ = subBuilder.buildPartial();
            }

            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            priceType_ = rawValue;
            break;
          }
          case 88: {
            int rawValue = input.readEnum();

            side_ = rawValue;
            break;
          }
          case 96: {

            volume_ = input.readInt64();
            break;
          }
          case 104: {

            matchedVolume_ = input.readInt64();
            break;
          }
          case 112: {

            balanceVolume_ = input.readInt64();
            break;
          }
          case 120: {

            cancelledVolume_ = input.readInt64();
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 136: {

            canCancel_ = input.readBool();
            break;
          }
          case 144: {

            canChange_ = input.readBool();
            break;
          }
          case 152: {

            canChangePriceVol_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.settrade.openapi.protobuf.v1.OrderEquityV1Proto.internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.settrade.openapi.protobuf.v1.OrderEquityV1Proto.internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.settrade.openapi.protobuf.v1.OrderEquityV1.class, com.settrade.openapi.protobuf.v1.OrderEquityV1.Builder.class);
  }

  /**
   * Protobuf enum {@code settrade.openapi.protobuf.v1.OrderEquityV1.PriceType}
   */
  public enum PriceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNDEFINED_PRICE_TYPE = 0;</code>
     */
    UNDEFINED_PRICE_TYPE(0),
    /**
     * <code>LIMIT = 1;</code>
     */
    LIMIT(1),
    /**
     * <code>ATO = 2;</code>
     */
    ATO(2),
    /**
     * <code>ATC = 3;</code>
     */
    ATC(3),
    /**
     * <code>MARKET = 4;</code>
     */
    MARKET(4),
    /**
     * <code>SPECIAL_MARKET = 5;</code>
     */
    SPECIAL_MARKET(5),
    /**
     * <code>MARKET_TO_LIMIT = 6;</code>
     */
    MARKET_TO_LIMIT(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNDEFINED_PRICE_TYPE = 0;</code>
     */
    public static final int UNDEFINED_PRICE_TYPE_VALUE = 0;
    /**
     * <code>LIMIT = 1;</code>
     */
    public static final int LIMIT_VALUE = 1;
    /**
     * <code>ATO = 2;</code>
     */
    public static final int ATO_VALUE = 2;
    /**
     * <code>ATC = 3;</code>
     */
    public static final int ATC_VALUE = 3;
    /**
     * <code>MARKET = 4;</code>
     */
    public static final int MARKET_VALUE = 4;
    /**
     * <code>SPECIAL_MARKET = 5;</code>
     */
    public static final int SPECIAL_MARKET_VALUE = 5;
    /**
     * <code>MARKET_TO_LIMIT = 6;</code>
     */
    public static final int MARKET_TO_LIMIT_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PriceType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PriceType forNumber(int value) {
      switch (value) {
        case 0: return UNDEFINED_PRICE_TYPE;
        case 1: return LIMIT;
        case 2: return ATO;
        case 3: return ATC;
        case 4: return MARKET;
        case 5: return SPECIAL_MARKET;
        case 6: return MARKET_TO_LIMIT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PriceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PriceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PriceType>() {
            public PriceType findValueByNumber(int number) {
              return PriceType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.settrade.openapi.protobuf.v1.OrderEquityV1.getDescriptor().getEnumTypes().get(0);
    }

    private static final PriceType[] VALUES = values();

    public static PriceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PriceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:settrade.openapi.protobuf.v1.OrderEquityV1.PriceType)
  }

  /**
   * Protobuf enum {@code settrade.openapi.protobuf.v1.OrderEquityV1.BuySell}
   */
  public enum BuySell
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNDEFINED_BUYSELL = 0;</code>
     */
    UNDEFINED_BUYSELL(0),
    /**
     * <code>BUY = 1;</code>
     */
    BUY(1),
    /**
     * <code>SELL = 2;</code>
     */
    SELL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNDEFINED_BUYSELL = 0;</code>
     */
    public static final int UNDEFINED_BUYSELL_VALUE = 0;
    /**
     * <code>BUY = 1;</code>
     */
    public static final int BUY_VALUE = 1;
    /**
     * <code>SELL = 2;</code>
     */
    public static final int SELL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BuySell valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BuySell forNumber(int value) {
      switch (value) {
        case 0: return UNDEFINED_BUYSELL;
        case 1: return BUY;
        case 2: return SELL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BuySell>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BuySell> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BuySell>() {
            public BuySell findValueByNumber(int number) {
              return BuySell.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.settrade.openapi.protobuf.v1.OrderEquityV1.getDescriptor().getEnumTypes().get(1);
    }

    private static final BuySell[] VALUES = values();

    public static BuySell valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BuySell(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:settrade.openapi.protobuf.v1.OrderEquityV1.BuySell)
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <pre>
   * Order version. Greater version means more recent order
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  public int getVersion() {
    return version_;
  }

  public static final int ORDER_NO_FIELD_NUMBER = 2;
  private volatile java.lang.Object orderNo_;
  /**
   * <pre>
   * Settrade Order No.
   * </pre>
   *
   * <code>string order_no = 2;</code>
   * @return The orderNo.
   */
  public java.lang.String getOrderNo() {
    java.lang.Object ref = orderNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderNo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Settrade Order No.
   * </pre>
   *
   * <code>string order_no = 2;</code>
   * @return The bytes for orderNo.
   */
  public com.google.protobuf.ByteString
      getOrderNoBytes() {
    java.lang.Object ref = orderNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXT_ORDER_NO_FIELD_NUMBER = 3;
  private volatile java.lang.Object extOrderNo_;
  /**
   * <pre>
   * External order no. in case of using integrated account, otherwise blank
   * </pre>
   *
   * <code>string ext_order_no = 3;</code>
   * @return The extOrderNo.
   */
  public java.lang.String getExtOrderNo() {
    java.lang.Object ref = extOrderNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extOrderNo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * External order no. in case of using integrated account, otherwise blank
   * </pre>
   *
   * <code>string ext_order_no = 3;</code>
   * @return The bytes for extOrderNo.
   */
  public com.google.protobuf.ByteString
      getExtOrderNoBytes() {
    java.lang.Object ref = extOrderNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extOrderNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_NO_FIELD_NUMBER = 4;
  private volatile java.lang.Object accountNo_;
  /**
   * <pre>
   * Subscribed account no.
   * </pre>
   *
   * <code>string account_no = 4;</code>
   * @return The accountNo.
   */
  public java.lang.String getAccountNo() {
    java.lang.Object ref = accountNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountNo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Subscribed account no.
   * </pre>
   *
   * <code>string account_no = 4;</code>
   * @return The bytes for accountNo.
   */
  public com.google.protobuf.ByteString
      getAccountNoBytes() {
    java.lang.Object ref = accountNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTRY_TIME_FIELD_NUMBER = 5;
  private com.google.type.TimeOfDay entryTime_;
  /**
   * <pre>
   * The time the order is submitted
   * </pre>
   *
   * <code>.google.type.TimeOfDay entry_time = 5;</code>
   * @return Whether the entryTime field is set.
   */
  public boolean hasEntryTime() {
    return entryTime_ != null;
  }
  /**
   * <pre>
   * The time the order is submitted
   * </pre>
   *
   * <code>.google.type.TimeOfDay entry_time = 5;</code>
   * @return The entryTime.
   */
  public com.google.type.TimeOfDay getEntryTime() {
    return entryTime_ == null ? com.google.type.TimeOfDay.getDefaultInstance() : entryTime_;
  }
  /**
   * <pre>
   * The time the order is submitted
   * </pre>
   *
   * <code>.google.type.TimeOfDay entry_time = 5;</code>
   */
  public com.google.type.TimeOfDayOrBuilder getEntryTimeOrBuilder() {
    return getEntryTime();
  }

  public static final int TRADE_DATE_FIELD_NUMBER = 6;
  private com.google.type.Date tradeDate_;
  /**
   * <pre>
   * Order Trade Date
   * </pre>
   *
   * <code>.google.type.Date trade_date = 6;</code>
   * @return Whether the tradeDate field is set.
   */
  public boolean hasTradeDate() {
    return tradeDate_ != null;
  }
  /**
   * <pre>
   * Order Trade Date
   * </pre>
   *
   * <code>.google.type.Date trade_date = 6;</code>
   * @return The tradeDate.
   */
  public com.google.type.Date getTradeDate() {
    return tradeDate_ == null ? com.google.type.Date.getDefaultInstance() : tradeDate_;
  }
  /**
   * <pre>
   * Order Trade Date
   * </pre>
   *
   * <code>.google.type.Date trade_date = 6;</code>
   */
  public com.google.type.DateOrBuilder getTradeDateOrBuilder() {
    return getTradeDate();
  }

  public static final int SYMBOL_FIELD_NUMBER = 7;
  private volatile java.lang.Object symbol_;
  /**
   * <pre>
   * Order Symbol
   * </pre>
   *
   * <code>string symbol = 7;</code>
   * @return The symbol.
   */
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Order Symbol
   * </pre>
   *
   * <code>string symbol = 7;</code>
   * @return The bytes for symbol.
   */
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_NVDR_FIELD_NUMBER = 8;
  private boolean isNvdr_;
  /**
   * <pre>
   * True if this is an NVDR order, false otherwise
   * </pre>
   *
   * <code>bool is_nvdr = 8;</code>
   * @return The isNvdr.
   */
  public boolean getIsNvdr() {
    return isNvdr_;
  }

  public static final int PRICE_FIELD_NUMBER = 9;
  private com.google.type.Money price_;
  /**
   * <pre>
   * Order Price
   * </pre>
   *
   * <code>.google.type.Money price = 9;</code>
   * @return Whether the price field is set.
   */
  public boolean hasPrice() {
    return price_ != null;
  }
  /**
   * <pre>
   * Order Price
   * </pre>
   *
   * <code>.google.type.Money price = 9;</code>
   * @return The price.
   */
  public com.google.type.Money getPrice() {
    return price_ == null ? com.google.type.Money.getDefaultInstance() : price_;
  }
  /**
   * <pre>
   * Order Price
   * </pre>
   *
   * <code>.google.type.Money price = 9;</code>
   */
  public com.google.type.MoneyOrBuilder getPriceOrBuilder() {
    return getPrice();
  }

  public static final int PRICE_TYPE_FIELD_NUMBER = 10;
  private int priceType_;
  /**
   * <pre>
   * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType price_type = 10;</code>
   * @return The enum numeric value on the wire for priceType.
   */
  public int getPriceTypeValue() {
    return priceType_;
  }
  /**
   * <pre>
   * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType price_type = 10;</code>
   * @return The priceType.
   */
  public com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType getPriceType() {
    @SuppressWarnings("deprecation")
    com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType result = com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType.valueOf(priceType_);
    return result == null ? com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType.UNRECOGNIZED : result;
  }

  public static final int SIDE_FIELD_NUMBER = 11;
  private int side_;
  /**
   * <pre>
   * Side - Buy or Sell
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell side = 11;</code>
   * @return The enum numeric value on the wire for side.
   */
  public int getSideValue() {
    return side_;
  }
  /**
   * <pre>
   * Side - Buy or Sell
   * </pre>
   *
   * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell side = 11;</code>
   * @return The side.
   */
  public com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell getSide() {
    @SuppressWarnings("deprecation")
    com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell result = com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell.valueOf(side_);
    return result == null ? com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell.UNRECOGNIZED : result;
  }

  public static final int VOLUME_FIELD_NUMBER = 12;
  private long volume_;
  /**
   * <pre>
   * Order Volume
   * </pre>
   *
   * <code>int64 volume = 12;</code>
   * @return The volume.
   */
  public long getVolume() {
    return volume_;
  }

  public static final int MATCHED_VOLUME_FIELD_NUMBER = 13;
  private long matchedVolume_;
  /**
   * <pre>
   * Order Matched Volume
   * </pre>
   *
   * <code>int64 matched_volume = 13;</code>
   * @return The matchedVolume.
   */
  public long getMatchedVolume() {
    return matchedVolume_;
  }

  public static final int BALANCE_VOLUME_FIELD_NUMBER = 14;
  private long balanceVolume_;
  /**
   * <pre>
   * Order Balance Volume
   * Balance Volume = Order Volume - Matched Volume - Cancelled Volume
   * </pre>
   *
   * <code>int64 balance_volume = 14;</code>
   * @return The balanceVolume.
   */
  public long getBalanceVolume() {
    return balanceVolume_;
  }

  public static final int CANCELLED_VOLUME_FIELD_NUMBER = 15;
  private long cancelledVolume_;
  /**
   * <pre>
   * Order Cancelled Volume
   * </pre>
   *
   * <code>int64 cancelled_volume = 15;</code>
   * @return The cancelledVolume.
   */
  public long getCancelledVolume() {
    return cancelledVolume_;
  }

  public static final int STATUS_FIELD_NUMBER = 16;
  private volatile java.lang.Object status_;
  /**
   * <pre>
   * Order Status
   * </pre>
   *
   * <code>string status = 16;</code>
   * @return The status.
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Order Status
   * </pre>
   *
   * <code>string status = 16;</code>
   * @return The bytes for status.
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAN_CANCEL_FIELD_NUMBER = 17;
  private boolean canCancel_;
  /**
   * <pre>
   * True if available for cancel, false otherwise
   * </pre>
   *
   * <code>bool can_cancel = 17;</code>
   * @return The canCancel.
   */
  public boolean getCanCancel() {
    return canCancel_;
  }

  public static final int CAN_CHANGE_FIELD_NUMBER = 18;
  private boolean canChange_;
  /**
   * <pre>
   * True if available for change nvdr, false otherwise
   * </pre>
   *
   * <code>bool can_change = 18;</code>
   * @return The canChange.
   */
  public boolean getCanChange() {
    return canChange_;
  }

  public static final int CAN_CHANGE_PRICE_VOL_FIELD_NUMBER = 19;
  private boolean canChangePriceVol_;
  /**
   * <pre>
   * True if available for change price/volume, false otherwise
   * </pre>
   *
   * <code>bool can_change_price_vol = 19;</code>
   * @return The canChangePriceVol.
   */
  public boolean getCanChangePriceVol() {
    return canChangePriceVol_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (!getOrderNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderNo_);
    }
    if (!getExtOrderNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, extOrderNo_);
    }
    if (!getAccountNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accountNo_);
    }
    if (entryTime_ != null) {
      output.writeMessage(5, getEntryTime());
    }
    if (tradeDate_ != null) {
      output.writeMessage(6, getTradeDate());
    }
    if (!getSymbolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, symbol_);
    }
    if (isNvdr_ != false) {
      output.writeBool(8, isNvdr_);
    }
    if (price_ != null) {
      output.writeMessage(9, getPrice());
    }
    if (priceType_ != com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType.UNDEFINED_PRICE_TYPE.getNumber()) {
      output.writeEnum(10, priceType_);
    }
    if (side_ != com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell.UNDEFINED_BUYSELL.getNumber()) {
      output.writeEnum(11, side_);
    }
    if (volume_ != 0L) {
      output.writeInt64(12, volume_);
    }
    if (matchedVolume_ != 0L) {
      output.writeInt64(13, matchedVolume_);
    }
    if (balanceVolume_ != 0L) {
      output.writeInt64(14, balanceVolume_);
    }
    if (cancelledVolume_ != 0L) {
      output.writeInt64(15, cancelledVolume_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, status_);
    }
    if (canCancel_ != false) {
      output.writeBool(17, canCancel_);
    }
    if (canChange_ != false) {
      output.writeBool(18, canChange_);
    }
    if (canChangePriceVol_ != false) {
      output.writeBool(19, canChangePriceVol_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (!getOrderNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderNo_);
    }
    if (!getExtOrderNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, extOrderNo_);
    }
    if (!getAccountNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accountNo_);
    }
    if (entryTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getEntryTime());
    }
    if (tradeDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTradeDate());
    }
    if (!getSymbolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, symbol_);
    }
    if (isNvdr_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isNvdr_);
    }
    if (price_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getPrice());
    }
    if (priceType_ != com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType.UNDEFINED_PRICE_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, priceType_);
    }
    if (side_ != com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell.UNDEFINED_BUYSELL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, side_);
    }
    if (volume_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, volume_);
    }
    if (matchedVolume_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, matchedVolume_);
    }
    if (balanceVolume_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, balanceVolume_);
    }
    if (cancelledVolume_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(15, cancelledVolume_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, status_);
    }
    if (canCancel_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(17, canCancel_);
    }
    if (canChange_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(18, canChange_);
    }
    if (canChangePriceVol_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(19, canChangePriceVol_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.settrade.openapi.protobuf.v1.OrderEquityV1)) {
      return super.equals(obj);
    }
    com.settrade.openapi.protobuf.v1.OrderEquityV1 other = (com.settrade.openapi.protobuf.v1.OrderEquityV1) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getOrderNo()
        .equals(other.getOrderNo())) return false;
    if (!getExtOrderNo()
        .equals(other.getExtOrderNo())) return false;
    if (!getAccountNo()
        .equals(other.getAccountNo())) return false;
    if (hasEntryTime() != other.hasEntryTime()) return false;
    if (hasEntryTime()) {
      if (!getEntryTime()
          .equals(other.getEntryTime())) return false;
    }
    if (hasTradeDate() != other.hasTradeDate()) return false;
    if (hasTradeDate()) {
      if (!getTradeDate()
          .equals(other.getTradeDate())) return false;
    }
    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (getIsNvdr()
        != other.getIsNvdr()) return false;
    if (hasPrice() != other.hasPrice()) return false;
    if (hasPrice()) {
      if (!getPrice()
          .equals(other.getPrice())) return false;
    }
    if (priceType_ != other.priceType_) return false;
    if (side_ != other.side_) return false;
    if (getVolume()
        != other.getVolume()) return false;
    if (getMatchedVolume()
        != other.getMatchedVolume()) return false;
    if (getBalanceVolume()
        != other.getBalanceVolume()) return false;
    if (getCancelledVolume()
        != other.getCancelledVolume()) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (getCanCancel()
        != other.getCanCancel()) return false;
    if (getCanChange()
        != other.getCanChange()) return false;
    if (getCanChangePriceVol()
        != other.getCanChangePriceVol()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + ORDER_NO_FIELD_NUMBER;
    hash = (53 * hash) + getOrderNo().hashCode();
    hash = (37 * hash) + EXT_ORDER_NO_FIELD_NUMBER;
    hash = (53 * hash) + getExtOrderNo().hashCode();
    hash = (37 * hash) + ACCOUNT_NO_FIELD_NUMBER;
    hash = (53 * hash) + getAccountNo().hashCode();
    if (hasEntryTime()) {
      hash = (37 * hash) + ENTRY_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getEntryTime().hashCode();
    }
    if (hasTradeDate()) {
      hash = (37 * hash) + TRADE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getTradeDate().hashCode();
    }
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + IS_NVDR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsNvdr());
    if (hasPrice()) {
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice().hashCode();
    }
    hash = (37 * hash) + PRICE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + priceType_;
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + side_;
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVolume());
    hash = (37 * hash) + MATCHED_VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMatchedVolume());
    hash = (37 * hash) + BALANCE_VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBalanceVolume());
    hash = (37 * hash) + CANCELLED_VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCancelledVolume());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + CAN_CANCEL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCanCancel());
    hash = (37 * hash) + CAN_CHANGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCanChange());
    hash = (37 * hash) + CAN_CHANGE_PRICE_VOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCanChangePriceVol());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.settrade.openapi.protobuf.v1.OrderEquityV1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Topic: proto/ua/_broker/&lt;account_no&gt;/_front/ordereqv1
   * Equity order information
   * </pre>
   *
   * Protobuf type {@code settrade.openapi.protobuf.v1.OrderEquityV1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:settrade.openapi.protobuf.v1.OrderEquityV1)
      com.settrade.openapi.protobuf.v1.OrderEquityV1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.settrade.openapi.protobuf.v1.OrderEquityV1Proto.internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.settrade.openapi.protobuf.v1.OrderEquityV1Proto.internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.settrade.openapi.protobuf.v1.OrderEquityV1.class, com.settrade.openapi.protobuf.v1.OrderEquityV1.Builder.class);
    }

    // Construct using com.settrade.openapi.protobuf.v1.OrderEquityV1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      orderNo_ = "";

      extOrderNo_ = "";

      accountNo_ = "";

      if (entryTimeBuilder_ == null) {
        entryTime_ = null;
      } else {
        entryTime_ = null;
        entryTimeBuilder_ = null;
      }
      if (tradeDateBuilder_ == null) {
        tradeDate_ = null;
      } else {
        tradeDate_ = null;
        tradeDateBuilder_ = null;
      }
      symbol_ = "";

      isNvdr_ = false;

      if (priceBuilder_ == null) {
        price_ = null;
      } else {
        price_ = null;
        priceBuilder_ = null;
      }
      priceType_ = 0;

      side_ = 0;

      volume_ = 0L;

      matchedVolume_ = 0L;

      balanceVolume_ = 0L;

      cancelledVolume_ = 0L;

      status_ = "";

      canCancel_ = false;

      canChange_ = false;

      canChangePriceVol_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.settrade.openapi.protobuf.v1.OrderEquityV1Proto.internal_static_settrade_openapi_protobuf_v1_OrderEquityV1_descriptor;
    }

    @java.lang.Override
    public com.settrade.openapi.protobuf.v1.OrderEquityV1 getDefaultInstanceForType() {
      return com.settrade.openapi.protobuf.v1.OrderEquityV1.getDefaultInstance();
    }

    @java.lang.Override
    public com.settrade.openapi.protobuf.v1.OrderEquityV1 build() {
      com.settrade.openapi.protobuf.v1.OrderEquityV1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.settrade.openapi.protobuf.v1.OrderEquityV1 buildPartial() {
      com.settrade.openapi.protobuf.v1.OrderEquityV1 result = new com.settrade.openapi.protobuf.v1.OrderEquityV1(this);
      result.version_ = version_;
      result.orderNo_ = orderNo_;
      result.extOrderNo_ = extOrderNo_;
      result.accountNo_ = accountNo_;
      if (entryTimeBuilder_ == null) {
        result.entryTime_ = entryTime_;
      } else {
        result.entryTime_ = entryTimeBuilder_.build();
      }
      if (tradeDateBuilder_ == null) {
        result.tradeDate_ = tradeDate_;
      } else {
        result.tradeDate_ = tradeDateBuilder_.build();
      }
      result.symbol_ = symbol_;
      result.isNvdr_ = isNvdr_;
      if (priceBuilder_ == null) {
        result.price_ = price_;
      } else {
        result.price_ = priceBuilder_.build();
      }
      result.priceType_ = priceType_;
      result.side_ = side_;
      result.volume_ = volume_;
      result.matchedVolume_ = matchedVolume_;
      result.balanceVolume_ = balanceVolume_;
      result.cancelledVolume_ = cancelledVolume_;
      result.status_ = status_;
      result.canCancel_ = canCancel_;
      result.canChange_ = canChange_;
      result.canChangePriceVol_ = canChangePriceVol_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.settrade.openapi.protobuf.v1.OrderEquityV1) {
        return mergeFrom((com.settrade.openapi.protobuf.v1.OrderEquityV1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.settrade.openapi.protobuf.v1.OrderEquityV1 other) {
      if (other == com.settrade.openapi.protobuf.v1.OrderEquityV1.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (!other.getOrderNo().isEmpty()) {
        orderNo_ = other.orderNo_;
        onChanged();
      }
      if (!other.getExtOrderNo().isEmpty()) {
        extOrderNo_ = other.extOrderNo_;
        onChanged();
      }
      if (!other.getAccountNo().isEmpty()) {
        accountNo_ = other.accountNo_;
        onChanged();
      }
      if (other.hasEntryTime()) {
        mergeEntryTime(other.getEntryTime());
      }
      if (other.hasTradeDate()) {
        mergeTradeDate(other.getTradeDate());
      }
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        onChanged();
      }
      if (other.getIsNvdr() != false) {
        setIsNvdr(other.getIsNvdr());
      }
      if (other.hasPrice()) {
        mergePrice(other.getPrice());
      }
      if (other.priceType_ != 0) {
        setPriceTypeValue(other.getPriceTypeValue());
      }
      if (other.side_ != 0) {
        setSideValue(other.getSideValue());
      }
      if (other.getVolume() != 0L) {
        setVolume(other.getVolume());
      }
      if (other.getMatchedVolume() != 0L) {
        setMatchedVolume(other.getMatchedVolume());
      }
      if (other.getBalanceVolume() != 0L) {
        setBalanceVolume(other.getBalanceVolume());
      }
      if (other.getCancelledVolume() != 0L) {
        setCancelledVolume(other.getCancelledVolume());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (other.getCanCancel() != false) {
        setCanCancel(other.getCanCancel());
      }
      if (other.getCanChange() != false) {
        setCanChange(other.getCanChange());
      }
      if (other.getCanChangePriceVol() != false) {
        setCanChangePriceVol(other.getCanChangePriceVol());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.settrade.openapi.protobuf.v1.OrderEquityV1 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.settrade.openapi.protobuf.v1.OrderEquityV1) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int version_ ;
    /**
     * <pre>
     * Order version. Greater version means more recent order
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     * Order version. Greater version means more recent order
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order version. Greater version means more recent order
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object orderNo_ = "";
    /**
     * <pre>
     * Settrade Order No.
     * </pre>
     *
     * <code>string order_no = 2;</code>
     * @return The orderNo.
     */
    public java.lang.String getOrderNo() {
      java.lang.Object ref = orderNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Settrade Order No.
     * </pre>
     *
     * <code>string order_no = 2;</code>
     * @return The bytes for orderNo.
     */
    public com.google.protobuf.ByteString
        getOrderNoBytes() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Settrade Order No.
     * </pre>
     *
     * <code>string order_no = 2;</code>
     * @param value The orderNo to set.
     * @return This builder for chaining.
     */
    public Builder setOrderNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Settrade Order No.
     * </pre>
     *
     * <code>string order_no = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderNo() {
      
      orderNo_ = getDefaultInstance().getOrderNo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Settrade Order No.
     * </pre>
     *
     * <code>string order_no = 2;</code>
     * @param value The bytes for orderNo to set.
     * @return This builder for chaining.
     */
    public Builder setOrderNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object extOrderNo_ = "";
    /**
     * <pre>
     * External order no. in case of using integrated account, otherwise blank
     * </pre>
     *
     * <code>string ext_order_no = 3;</code>
     * @return The extOrderNo.
     */
    public java.lang.String getExtOrderNo() {
      java.lang.Object ref = extOrderNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extOrderNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * External order no. in case of using integrated account, otherwise blank
     * </pre>
     *
     * <code>string ext_order_no = 3;</code>
     * @return The bytes for extOrderNo.
     */
    public com.google.protobuf.ByteString
        getExtOrderNoBytes() {
      java.lang.Object ref = extOrderNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extOrderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * External order no. in case of using integrated account, otherwise blank
     * </pre>
     *
     * <code>string ext_order_no = 3;</code>
     * @param value The extOrderNo to set.
     * @return This builder for chaining.
     */
    public Builder setExtOrderNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extOrderNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * External order no. in case of using integrated account, otherwise blank
     * </pre>
     *
     * <code>string ext_order_no = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtOrderNo() {
      
      extOrderNo_ = getDefaultInstance().getExtOrderNo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * External order no. in case of using integrated account, otherwise blank
     * </pre>
     *
     * <code>string ext_order_no = 3;</code>
     * @param value The bytes for extOrderNo to set.
     * @return This builder for chaining.
     */
    public Builder setExtOrderNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extOrderNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accountNo_ = "";
    /**
     * <pre>
     * Subscribed account no.
     * </pre>
     *
     * <code>string account_no = 4;</code>
     * @return The accountNo.
     */
    public java.lang.String getAccountNo() {
      java.lang.Object ref = accountNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Subscribed account no.
     * </pre>
     *
     * <code>string account_no = 4;</code>
     * @return The bytes for accountNo.
     */
    public com.google.protobuf.ByteString
        getAccountNoBytes() {
      java.lang.Object ref = accountNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Subscribed account no.
     * </pre>
     *
     * <code>string account_no = 4;</code>
     * @param value The accountNo to set.
     * @return This builder for chaining.
     */
    public Builder setAccountNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Subscribed account no.
     * </pre>
     *
     * <code>string account_no = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountNo() {
      
      accountNo_ = getDefaultInstance().getAccountNo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Subscribed account no.
     * </pre>
     *
     * <code>string account_no = 4;</code>
     * @param value The bytes for accountNo to set.
     * @return This builder for chaining.
     */
    public Builder setAccountNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountNo_ = value;
      onChanged();
      return this;
    }

    private com.google.type.TimeOfDay entryTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.TimeOfDay, com.google.type.TimeOfDay.Builder, com.google.type.TimeOfDayOrBuilder> entryTimeBuilder_;
    /**
     * <pre>
     * The time the order is submitted
     * </pre>
     *
     * <code>.google.type.TimeOfDay entry_time = 5;</code>
     * @return Whether the entryTime field is set.
     */
    public boolean hasEntryTime() {
      return entryTimeBuilder_ != null || entryTime_ != null;
    }
    /**
     * <pre>
     * The time the order is submitted
     * </pre>
     *
     * <code>.google.type.TimeOfDay entry_time = 5;</code>
     * @return The entryTime.
     */
    public com.google.type.TimeOfDay getEntryTime() {
      if (entryTimeBuilder_ == null) {
        return entryTime_ == null ? com.google.type.TimeOfDay.getDefaultInstance() : entryTime_;
      } else {
        return entryTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The time the order is submitted
     * </pre>
     *
     * <code>.google.type.TimeOfDay entry_time = 5;</code>
     */
    public Builder setEntryTime(com.google.type.TimeOfDay value) {
      if (entryTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        entryTime_ = value;
        onChanged();
      } else {
        entryTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The time the order is submitted
     * </pre>
     *
     * <code>.google.type.TimeOfDay entry_time = 5;</code>
     */
    public Builder setEntryTime(
        com.google.type.TimeOfDay.Builder builderForValue) {
      if (entryTimeBuilder_ == null) {
        entryTime_ = builderForValue.build();
        onChanged();
      } else {
        entryTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The time the order is submitted
     * </pre>
     *
     * <code>.google.type.TimeOfDay entry_time = 5;</code>
     */
    public Builder mergeEntryTime(com.google.type.TimeOfDay value) {
      if (entryTimeBuilder_ == null) {
        if (entryTime_ != null) {
          entryTime_ =
            com.google.type.TimeOfDay.newBuilder(entryTime_).mergeFrom(value).buildPartial();
        } else {
          entryTime_ = value;
        }
        onChanged();
      } else {
        entryTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The time the order is submitted
     * </pre>
     *
     * <code>.google.type.TimeOfDay entry_time = 5;</code>
     */
    public Builder clearEntryTime() {
      if (entryTimeBuilder_ == null) {
        entryTime_ = null;
        onChanged();
      } else {
        entryTime_ = null;
        entryTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The time the order is submitted
     * </pre>
     *
     * <code>.google.type.TimeOfDay entry_time = 5;</code>
     */
    public com.google.type.TimeOfDay.Builder getEntryTimeBuilder() {
      
      onChanged();
      return getEntryTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The time the order is submitted
     * </pre>
     *
     * <code>.google.type.TimeOfDay entry_time = 5;</code>
     */
    public com.google.type.TimeOfDayOrBuilder getEntryTimeOrBuilder() {
      if (entryTimeBuilder_ != null) {
        return entryTimeBuilder_.getMessageOrBuilder();
      } else {
        return entryTime_ == null ?
            com.google.type.TimeOfDay.getDefaultInstance() : entryTime_;
      }
    }
    /**
     * <pre>
     * The time the order is submitted
     * </pre>
     *
     * <code>.google.type.TimeOfDay entry_time = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.TimeOfDay, com.google.type.TimeOfDay.Builder, com.google.type.TimeOfDayOrBuilder> 
        getEntryTimeFieldBuilder() {
      if (entryTimeBuilder_ == null) {
        entryTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.TimeOfDay, com.google.type.TimeOfDay.Builder, com.google.type.TimeOfDayOrBuilder>(
                getEntryTime(),
                getParentForChildren(),
                isClean());
        entryTime_ = null;
      }
      return entryTimeBuilder_;
    }

    private com.google.type.Date tradeDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder> tradeDateBuilder_;
    /**
     * <pre>
     * Order Trade Date
     * </pre>
     *
     * <code>.google.type.Date trade_date = 6;</code>
     * @return Whether the tradeDate field is set.
     */
    public boolean hasTradeDate() {
      return tradeDateBuilder_ != null || tradeDate_ != null;
    }
    /**
     * <pre>
     * Order Trade Date
     * </pre>
     *
     * <code>.google.type.Date trade_date = 6;</code>
     * @return The tradeDate.
     */
    public com.google.type.Date getTradeDate() {
      if (tradeDateBuilder_ == null) {
        return tradeDate_ == null ? com.google.type.Date.getDefaultInstance() : tradeDate_;
      } else {
        return tradeDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Order Trade Date
     * </pre>
     *
     * <code>.google.type.Date trade_date = 6;</code>
     */
    public Builder setTradeDate(com.google.type.Date value) {
      if (tradeDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tradeDate_ = value;
        onChanged();
      } else {
        tradeDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Order Trade Date
     * </pre>
     *
     * <code>.google.type.Date trade_date = 6;</code>
     */
    public Builder setTradeDate(
        com.google.type.Date.Builder builderForValue) {
      if (tradeDateBuilder_ == null) {
        tradeDate_ = builderForValue.build();
        onChanged();
      } else {
        tradeDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Order Trade Date
     * </pre>
     *
     * <code>.google.type.Date trade_date = 6;</code>
     */
    public Builder mergeTradeDate(com.google.type.Date value) {
      if (tradeDateBuilder_ == null) {
        if (tradeDate_ != null) {
          tradeDate_ =
            com.google.type.Date.newBuilder(tradeDate_).mergeFrom(value).buildPartial();
        } else {
          tradeDate_ = value;
        }
        onChanged();
      } else {
        tradeDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Order Trade Date
     * </pre>
     *
     * <code>.google.type.Date trade_date = 6;</code>
     */
    public Builder clearTradeDate() {
      if (tradeDateBuilder_ == null) {
        tradeDate_ = null;
        onChanged();
      } else {
        tradeDate_ = null;
        tradeDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Order Trade Date
     * </pre>
     *
     * <code>.google.type.Date trade_date = 6;</code>
     */
    public com.google.type.Date.Builder getTradeDateBuilder() {
      
      onChanged();
      return getTradeDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Order Trade Date
     * </pre>
     *
     * <code>.google.type.Date trade_date = 6;</code>
     */
    public com.google.type.DateOrBuilder getTradeDateOrBuilder() {
      if (tradeDateBuilder_ != null) {
        return tradeDateBuilder_.getMessageOrBuilder();
      } else {
        return tradeDate_ == null ?
            com.google.type.Date.getDefaultInstance() : tradeDate_;
      }
    }
    /**
     * <pre>
     * Order Trade Date
     * </pre>
     *
     * <code>.google.type.Date trade_date = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder> 
        getTradeDateFieldBuilder() {
      if (tradeDateBuilder_ == null) {
        tradeDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Date, com.google.type.Date.Builder, com.google.type.DateOrBuilder>(
                getTradeDate(),
                getParentForChildren(),
                isClean());
        tradeDate_ = null;
      }
      return tradeDateBuilder_;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <pre>
     * Order Symbol
     * </pre>
     *
     * <code>string symbol = 7;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Order Symbol
     * </pre>
     *
     * <code>string symbol = 7;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Order Symbol
     * </pre>
     *
     * <code>string symbol = 7;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Symbol
     * </pre>
     *
     * <code>string symbol = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      
      symbol_ = getDefaultInstance().getSymbol();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Symbol
     * </pre>
     *
     * <code>string symbol = 7;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      symbol_ = value;
      onChanged();
      return this;
    }

    private boolean isNvdr_ ;
    /**
     * <pre>
     * True if this is an NVDR order, false otherwise
     * </pre>
     *
     * <code>bool is_nvdr = 8;</code>
     * @return The isNvdr.
     */
    public boolean getIsNvdr() {
      return isNvdr_;
    }
    /**
     * <pre>
     * True if this is an NVDR order, false otherwise
     * </pre>
     *
     * <code>bool is_nvdr = 8;</code>
     * @param value The isNvdr to set.
     * @return This builder for chaining.
     */
    public Builder setIsNvdr(boolean value) {
      
      isNvdr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True if this is an NVDR order, false otherwise
     * </pre>
     *
     * <code>bool is_nvdr = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsNvdr() {
      
      isNvdr_ = false;
      onChanged();
      return this;
    }

    private com.google.type.Money price_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> priceBuilder_;
    /**
     * <pre>
     * Order Price
     * </pre>
     *
     * <code>.google.type.Money price = 9;</code>
     * @return Whether the price field is set.
     */
    public boolean hasPrice() {
      return priceBuilder_ != null || price_ != null;
    }
    /**
     * <pre>
     * Order Price
     * </pre>
     *
     * <code>.google.type.Money price = 9;</code>
     * @return The price.
     */
    public com.google.type.Money getPrice() {
      if (priceBuilder_ == null) {
        return price_ == null ? com.google.type.Money.getDefaultInstance() : price_;
      } else {
        return priceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Order Price
     * </pre>
     *
     * <code>.google.type.Money price = 9;</code>
     */
    public Builder setPrice(com.google.type.Money value) {
      if (priceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        price_ = value;
        onChanged();
      } else {
        priceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Order Price
     * </pre>
     *
     * <code>.google.type.Money price = 9;</code>
     */
    public Builder setPrice(
        com.google.type.Money.Builder builderForValue) {
      if (priceBuilder_ == null) {
        price_ = builderForValue.build();
        onChanged();
      } else {
        priceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Order Price
     * </pre>
     *
     * <code>.google.type.Money price = 9;</code>
     */
    public Builder mergePrice(com.google.type.Money value) {
      if (priceBuilder_ == null) {
        if (price_ != null) {
          price_ =
            com.google.type.Money.newBuilder(price_).mergeFrom(value).buildPartial();
        } else {
          price_ = value;
        }
        onChanged();
      } else {
        priceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Order Price
     * </pre>
     *
     * <code>.google.type.Money price = 9;</code>
     */
    public Builder clearPrice() {
      if (priceBuilder_ == null) {
        price_ = null;
        onChanged();
      } else {
        price_ = null;
        priceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Order Price
     * </pre>
     *
     * <code>.google.type.Money price = 9;</code>
     */
    public com.google.type.Money.Builder getPriceBuilder() {
      
      onChanged();
      return getPriceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Order Price
     * </pre>
     *
     * <code>.google.type.Money price = 9;</code>
     */
    public com.google.type.MoneyOrBuilder getPriceOrBuilder() {
      if (priceBuilder_ != null) {
        return priceBuilder_.getMessageOrBuilder();
      } else {
        return price_ == null ?
            com.google.type.Money.getDefaultInstance() : price_;
      }
    }
    /**
     * <pre>
     * Order Price
     * </pre>
     *
     * <code>.google.type.Money price = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder> 
        getPriceFieldBuilder() {
      if (priceBuilder_ == null) {
        priceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.type.Money, com.google.type.Money.Builder, com.google.type.MoneyOrBuilder>(
                getPrice(),
                getParentForChildren(),
                isClean());
        price_ = null;
      }
      return priceBuilder_;
    }

    private int priceType_ = 0;
    /**
     * <pre>
     * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType price_type = 10;</code>
     * @return The enum numeric value on the wire for priceType.
     */
    public int getPriceTypeValue() {
      return priceType_;
    }
    /**
     * <pre>
     * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType price_type = 10;</code>
     * @param value The enum numeric value on the wire for priceType to set.
     * @return This builder for chaining.
     */
    public Builder setPriceTypeValue(int value) {
      priceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType price_type = 10;</code>
     * @return The priceType.
     */
    public com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType getPriceType() {
      @SuppressWarnings("deprecation")
      com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType result = com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType.valueOf(priceType_);
      return result == null ? com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType price_type = 10;</code>
     * @param value The priceType to set.
     * @return This builder for chaining.
     */
    public Builder setPriceType(com.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      priceType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Price Type - Limit, ATO, ATC, Market (MP-MKT), Special Market (MP), Market to limit (MP-MTL)
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.PriceType price_type = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriceType() {
      
      priceType_ = 0;
      onChanged();
      return this;
    }

    private int side_ = 0;
    /**
     * <pre>
     * Side - Buy or Sell
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell side = 11;</code>
     * @return The enum numeric value on the wire for side.
     */
    public int getSideValue() {
      return side_;
    }
    /**
     * <pre>
     * Side - Buy or Sell
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell side = 11;</code>
     * @param value The enum numeric value on the wire for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideValue(int value) {
      side_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Side - Buy or Sell
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell side = 11;</code>
     * @return The side.
     */
    public com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell getSide() {
      @SuppressWarnings("deprecation")
      com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell result = com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell.valueOf(side_);
      return result == null ? com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Side - Buy or Sell
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell side = 11;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(com.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      side_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Side - Buy or Sell
     * </pre>
     *
     * <code>.settrade.openapi.protobuf.v1.OrderEquityV1.BuySell side = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      
      side_ = 0;
      onChanged();
      return this;
    }

    private long volume_ ;
    /**
     * <pre>
     * Order Volume
     * </pre>
     *
     * <code>int64 volume = 12;</code>
     * @return The volume.
     */
    public long getVolume() {
      return volume_;
    }
    /**
     * <pre>
     * Order Volume
     * </pre>
     *
     * <code>int64 volume = 12;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(long value) {
      
      volume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Volume
     * </pre>
     *
     * <code>int64 volume = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      
      volume_ = 0L;
      onChanged();
      return this;
    }

    private long matchedVolume_ ;
    /**
     * <pre>
     * Order Matched Volume
     * </pre>
     *
     * <code>int64 matched_volume = 13;</code>
     * @return The matchedVolume.
     */
    public long getMatchedVolume() {
      return matchedVolume_;
    }
    /**
     * <pre>
     * Order Matched Volume
     * </pre>
     *
     * <code>int64 matched_volume = 13;</code>
     * @param value The matchedVolume to set.
     * @return This builder for chaining.
     */
    public Builder setMatchedVolume(long value) {
      
      matchedVolume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Matched Volume
     * </pre>
     *
     * <code>int64 matched_volume = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearMatchedVolume() {
      
      matchedVolume_ = 0L;
      onChanged();
      return this;
    }

    private long balanceVolume_ ;
    /**
     * <pre>
     * Order Balance Volume
     * Balance Volume = Order Volume - Matched Volume - Cancelled Volume
     * </pre>
     *
     * <code>int64 balance_volume = 14;</code>
     * @return The balanceVolume.
     */
    public long getBalanceVolume() {
      return balanceVolume_;
    }
    /**
     * <pre>
     * Order Balance Volume
     * Balance Volume = Order Volume - Matched Volume - Cancelled Volume
     * </pre>
     *
     * <code>int64 balance_volume = 14;</code>
     * @param value The balanceVolume to set.
     * @return This builder for chaining.
     */
    public Builder setBalanceVolume(long value) {
      
      balanceVolume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Balance Volume
     * Balance Volume = Order Volume - Matched Volume - Cancelled Volume
     * </pre>
     *
     * <code>int64 balance_volume = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearBalanceVolume() {
      
      balanceVolume_ = 0L;
      onChanged();
      return this;
    }

    private long cancelledVolume_ ;
    /**
     * <pre>
     * Order Cancelled Volume
     * </pre>
     *
     * <code>int64 cancelled_volume = 15;</code>
     * @return The cancelledVolume.
     */
    public long getCancelledVolume() {
      return cancelledVolume_;
    }
    /**
     * <pre>
     * Order Cancelled Volume
     * </pre>
     *
     * <code>int64 cancelled_volume = 15;</code>
     * @param value The cancelledVolume to set.
     * @return This builder for chaining.
     */
    public Builder setCancelledVolume(long value) {
      
      cancelledVolume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Cancelled Volume
     * </pre>
     *
     * <code>int64 cancelled_volume = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearCancelledVolume() {
      
      cancelledVolume_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * Order Status
     * </pre>
     *
     * <code>string status = 16;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Order Status
     * </pre>
     *
     * <code>string status = 16;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Order Status
     * </pre>
     *
     * <code>string status = 16;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Status
     * </pre>
     *
     * <code>string status = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Order Status
     * </pre>
     *
     * <code>string status = 16;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private boolean canCancel_ ;
    /**
     * <pre>
     * True if available for cancel, false otherwise
     * </pre>
     *
     * <code>bool can_cancel = 17;</code>
     * @return The canCancel.
     */
    public boolean getCanCancel() {
      return canCancel_;
    }
    /**
     * <pre>
     * True if available for cancel, false otherwise
     * </pre>
     *
     * <code>bool can_cancel = 17;</code>
     * @param value The canCancel to set.
     * @return This builder for chaining.
     */
    public Builder setCanCancel(boolean value) {
      
      canCancel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True if available for cancel, false otherwise
     * </pre>
     *
     * <code>bool can_cancel = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanCancel() {
      
      canCancel_ = false;
      onChanged();
      return this;
    }

    private boolean canChange_ ;
    /**
     * <pre>
     * True if available for change nvdr, false otherwise
     * </pre>
     *
     * <code>bool can_change = 18;</code>
     * @return The canChange.
     */
    public boolean getCanChange() {
      return canChange_;
    }
    /**
     * <pre>
     * True if available for change nvdr, false otherwise
     * </pre>
     *
     * <code>bool can_change = 18;</code>
     * @param value The canChange to set.
     * @return This builder for chaining.
     */
    public Builder setCanChange(boolean value) {
      
      canChange_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True if available for change nvdr, false otherwise
     * </pre>
     *
     * <code>bool can_change = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanChange() {
      
      canChange_ = false;
      onChanged();
      return this;
    }

    private boolean canChangePriceVol_ ;
    /**
     * <pre>
     * True if available for change price/volume, false otherwise
     * </pre>
     *
     * <code>bool can_change_price_vol = 19;</code>
     * @return The canChangePriceVol.
     */
    public boolean getCanChangePriceVol() {
      return canChangePriceVol_;
    }
    /**
     * <pre>
     * True if available for change price/volume, false otherwise
     * </pre>
     *
     * <code>bool can_change_price_vol = 19;</code>
     * @param value The canChangePriceVol to set.
     * @return This builder for chaining.
     */
    public Builder setCanChangePriceVol(boolean value) {
      
      canChangePriceVol_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True if available for change price/volume, false otherwise
     * </pre>
     *
     * <code>bool can_change_price_vol = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanChangePriceVol() {
      
      canChangePriceVol_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:settrade.openapi.protobuf.v1.OrderEquityV1)
  }

  // @@protoc_insertion_point(class_scope:settrade.openapi.protobuf.v1.OrderEquityV1)
  private static final com.settrade.openapi.protobuf.v1.OrderEquityV1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.settrade.openapi.protobuf.v1.OrderEquityV1();
  }

  public static com.settrade.openapi.protobuf.v1.OrderEquityV1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderEquityV1>
      PARSER = new com.google.protobuf.AbstractParser<OrderEquityV1>() {
    @java.lang.Override
    public OrderEquityV1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderEquityV1(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderEquityV1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderEquityV1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.settrade.openapi.protobuf.v1.OrderEquityV1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

